workspace:
  base: /go/src
  path: github.com/appleboy/mgo-migrate

pipeline:
  backend:
    image: golang:1.10
    commands:
      - go get -v -t .
      - go test -v -cover -coverprofile coverage.out

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - coverage.out
    when:
      event: [ push, pull_request ]

services:
  mongodb:
    image: mongo:4.1-xenial
    environment:
      - MONGO_INITDB_DATABASE=test_migrate
